language: go
sudo: false
go:
  - 1.9
  - "1.10"
  - tip
env:
  - DEP_VERSION="0.3.2"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
before_script:
  - go vet ./...
script:
  - go build
  - bash ./travis.sh
after_script:
  - bash <(curl -s https://codecov.io/bash)
